packages:
  - claude-code
  - coreutils
  - docker
  - docker-compose

  # Raycast / Night Light

  - smudge/smudge/nightlight

  # yabai & skhd & JankyBorders

  - koekeishiya/formulae/skhd
  - koekeishiya/formulae/yabai

  - FelixKratz/formulae/borders
